// Package wrapper embeds the pre-built "adapted runtime" relay
// (cmd/fluxa-runtime-wrapper) that internal/portable assembles into every
// official Linux and macOS portable application. The embedded binaries are
// committed to the repository and regenerated by `make wrapper`;
// internal/wrapper's own test rebuilds each from source and compares
// hashes so a source change without regenerating the committed binaries
// fails CI instead of silently shipping stale code. See
// docs/adr/0025-linux-adapted-runtime-wrapper.md.
//
// The relay's logic is identical on every target (it is the same source,
// cross-compiled): plain Go stdlib process/argv/env handling with no
// platform-specific syscalls. The macOS binaries are cross-compiled and
// covered by the same drift test as Linux, but — unlike Linux — have not
// been exercised end to end on real macOS hardware; see the ADR for the
// exact scope of what is and is not verified.
package wrapper

import _ "embed"

// LinuxAMD64 is the compiled linux/amd64 fluxa-runtime-wrapper binary.
//
//go:embed bin/fluxa-runtime-wrapper-linux-amd64
var LinuxAMD64 []byte

// DarwinAMD64 is the compiled darwin/amd64 fluxa-runtime-wrapper binary.
//
//go:embed bin/fluxa-runtime-wrapper-darwin-amd64
var DarwinAMD64 []byte

// DarwinARM64 is the compiled darwin/arm64 fluxa-runtime-wrapper binary.
//
//go:embed bin/fluxa-runtime-wrapper-darwin-arm64
var DarwinARM64 []byte
