# Pinned build environment for fluxa-lang's Linux native build
# (make build FLUXA_GRAPH_RAYLIB=1 FLUXA_SOUND_MINIAUDIO=1), used by
# internal/toolchainbuild instead of the host's own package manager so the
# resulting binary never depends on host library *version* drift — see
# docs/adr/0027-automatic-toolchain-acquisition.md.
#
# Raylib has no Debian package on the base image this pins (confirmed:
# libraylib-dev does not exist on Debian bookworm/Ubuntu jammy), so it is
# built from the exact commit fluxa-lang's own Windows build script pins
# (platform/windows/build-raylib-static.sh), keeping the graphics backend
# identical across every platform this project builds for.
FROM debian:bookworm-slim

# Covers every std.* module fluxa.libs can realistically declare true
# that has a clean, self-contained static story — Linux's plain
# `make build` has no curated-profile restriction (unlike Windows's two
# static targets), so in principle any of the 29 stdlib modules could be
# requested. Two are deliberately absent here, in favor of fluxa-lang's
# own documented graceful degradation rather than fighting their static
# link graphs:
#
#   - libmosquitto-dev (std.mqtt): Ubuntu ships no static libmosquitto.a
#     at all, only a shared .so.
#   - libpq-dev (std.pg) and libmicrohttpd-dev (std.wserver): both do
#     have static archives, but real build attempts here found libpq.a
#     needs OpenSSL's own static libs transitively (undefined reference
#     to SSL_CIPHER_get_bits), the same class of problem raylib has below
#     — except fluxa.libs already documents both of these two as
#     "[stub if absent]", so leaving their dev packages out entirely and
#     letting the lib.mk's own pkg-config check silently fall back to the
#     stub backend is simpler and more robust than chasing a static
#     OpenSSL/GnuTLS dependency chain for a rarely-used module.
#
# A project enabling std.mqtt specifically (no stub fallback documented)
# falls back to the manual guide.
RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential python3 git pkg-config ca-certificates curl cmake \
      libsqlite3-dev libsodium-dev libcurl4-openssl-dev zlib1g-dev \
      libserialport-dev \
      libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev \
      libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev \
    && rm -rf /var/lib/apt/lists/*

# std.serial builds cleanly against a fully self-contained static archive
# (confirmed: libserialport.a's own Libs.private is empty, unlike
# libpq.a's or libcurl.a's much larger static dependency graphs). Its
# lib.mk calls plain, non-static `pkg-config --libs libserialport`, which
# resolves to whichever of libserialport.so/libserialport.a the linker
# finds first; removing the dev package's .so symlink (the runtime
# .so.N stays, untouched, for anything else on the system that needs it)
# makes that resolve to the static archive with no further flag changes
# needed, so the toolchain/runtime binary this produces never depends on
# it being present again on the machine it eventually runs on.
RUN rm -f /usr/lib/x86_64-linux-gnu/libserialport.so

# Raylib, static, installed to a system prefix so std.graph's own lib.mk
# finds it via `pkg-config --exists raylib` with no further configuration.
#
# fluxa-lang's lib.mk resolves raylib's link flags with plain
# `pkg-config --libs raylib` (not `--static --libs`), which only returns a
# library's *public* Libs: line — correct for a normal dynamic raylib
# package, where libraylib.so already carries its own transitive X11/GL
# dependencies at the ELF level. A static libraylib.a has no such
# self-contained resolution: the final binary must link every transitive
# dependency itself, or fail with undefined X11/GL symbols exactly as a
# real build attempt here confirmed. Since raylib.pc is generated by this
# same build (there is no distro package to defer to), its Libs: line is
# rewritten below to include the full static transitive dependency set
# directly, so the unmodified, plain pkg-config call already used
# upstream resolves correctly — no fluxa-lang source is patched.
ARG RAYLIB_COMMIT=dbc56a87da87d973a9c5baa4e7438a9d20121d28
RUN git clone https://github.com/raysan5/raylib.git /tmp/raylib \
    && git -C /tmp/raylib checkout "$RAYLIB_COMMIT" \
    && cmake -S /tmp/raylib -B /tmp/raylib/build \
         -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release \
    && cmake --build /tmp/raylib/build --parallel \
    && cmake --install /tmp/raylib/build --prefix /usr/local \
    && rm -rf /tmp/raylib \
    && sed -i \
         's|^Libs:.*|Libs: -L${libdir} -lraylib -lGL -lGLU -lm -lpthread -ldl -lrt -lX11 -lXrandr -lXinerama -lXi -lXcursor|' \
         /usr/local/lib/pkgconfig/raylib.pc

# Miniaudio is a single vendored header with no pkg-config fallback in
# std.sound's lib.mk (it only checks vendor/miniaudio.h inside the
# checkout) — internal/toolchainbuild copies this into the bind-mounted
# checkout's vendor/ directory before invoking make.
ARG MINIAUDIO_VERSION=0.11.21
RUN mkdir -p /opt/fluxa-vendor \
    && curl -fsSL -o /opt/fluxa-vendor/miniaudio.h \
       "https://raw.githubusercontent.com/mackron/miniaudio/${MINIAUDIO_VERSION}/miniaudio.h"
