// Package launcherbin embeds the pre-built cmd/fluxa-launcher binaries
// that internal/portable assembles into every portable application, one
// per supported target. The embedded binaries are committed to the
// repository and regenerated by `make launcher`; this package's own test
// rebuilds each from source and compares hashes, so a source change
// without regenerating the committed binaries fails CI instead of silently
// shipping a stale launcher — the same contract internal/wrapper already
// has for the runtime relay.
//
// Embedding them is what makes a cross-target build possible at all: a
// Windows application assembled on a Linux machine needs a PE launcher,
// and the running Fluxa Builder executable is an ELF. Copying that
// executable — what Fluxa Builder did before — produced an "application"
// whose .exe was an ELF wearing a Windows extension, which the PE
// subsystem patch then rejected outright with "unrecognized PE machine:
// 0x457f" (`\x7fE`, the ELF magic). See
// docs/adr/0029-cross-target-application-launcher.md.
package launcherbin

import (
	_ "embed"
	"fmt"
)

//go:embed bin/fluxa-launcher-linux-amd64
var linuxAMD64 []byte

//go:embed bin/fluxa-launcher-windows-amd64.exe
var windowsAMD64 []byte

//go:embed bin/fluxa-launcher-darwin-amd64
var darwinAMD64 []byte

//go:embed bin/fluxa-launcher-darwin-arm64
var darwinARM64 []byte

// For returns the launcher binary for a target OS/arch, using the same
// "macos" spelling for Apple targets that internal/manifest and the rest
// of this project use, not Go's own "darwin".
func For(targetOS, targetArch string) ([]byte, error) {
	switch {
	case targetOS == "linux" && targetArch == "amd64":
		return linuxAMD64, nil
	case targetOS == "windows" && targetArch == "amd64":
		return windowsAMD64, nil
	case targetOS == "macos" && targetArch == "amd64":
		return darwinAMD64, nil
	case targetOS == "macos" && targetArch == "arm64":
		return darwinARM64, nil
	default:
		return nil, fmt.Errorf("no embedded application launcher for %s/%s", targetOS, targetArch)
	}
}
